### ISSUE TITLE
possibilities to add two pulses

### ISSUE THREAD

**Issue by eendebakpt** [qutech/qupulse#396]
How can I add two pulses? I can concatenate pulses with the `@` operator, but there seems to be no `+` operator.

A minimal example:
```
import matplotlib.pyplot as plt
from qupulse.pulses import TablePT
from qupulse.pulses.plotting import plot

def plot_sequence(sequence, fig=100, *args, **kwargs):
    """ Pulse a qupulse sequence in a figure window """
    plt.figure(fig);plt.clf()
    ax=plt.gca()
    return plot(sequence, axes=ax, *args, **kwargs)

wave1 = TablePT({'0': [(0,0), (10, 1), (20,2), (30,0), (100,0)]})
wave2 = TablePT({'0': [(0,0), (50, -1), (60,0), (100,0)]})

plot_sequence(wave1, fig=100)
plot_sequence(wave2, fig=101)

plot_sequence(wave1 @ wave2, fig=200) #works
plot_sequence(wave1+wave2, fig=201) # generates an error
```

**Comment by lumip** [comment]
There is currently no `+` operator because we have not yet defined semantics for it. "Adding" pulse templates could be interpreted in several ways:

1.  Concatentation of the pulse templates (for that we currently have the `@` operator as you've pointed out)
2. "Stacking" of the pulse templates, i.e., merging two pulse templates defined on different channels into one pulse template
3. Adding of the voltage sequences defined on the same channels in the two pulse templates
4. Interleaving the voltage sequences defined on the same channel in the two pulse templates

With that, what would you expect as the result of wave1+wave2 in your example?

In my opinion, a mix of 2 and 3 would make sense but this is currently just not implemented. It should also be noted that implementing 3. is a very challenging task because of the many different possible variations of inputs to the `+` operator if we allow it to be usable for arbitrary PulseTemplate instances. We could maybe have a version that deals with atomic pulse templates (TablePT, FunctionPT, PointPT) only but even then, once parameters come into the mix, this is not trivial to implement..

**Comment by terrorfisch** [comment]
We have an issue open for arithmetics with PTs #262 

I did not come up with a satisfying solution yet.

**Comment by eendebakpt** [comment]
@lumip I was looking for option 3 (optionally with automatic zero padding if needed). Since #262 is there I will close the issue.
